//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThietBiCongTyEntities : DbContext
    {
        public QuanLyThietBiCongTyEntities()
            : base("name=QuanLyThietBiCongTyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PurTemDetailsTable> PurTemDetailsTables { get; set; }
        public virtual DbSet<tb_CHITIETNHAPHANG> tb_CHITIETNHAPHANG { get; set; }
        public virtual DbSet<tb_CHUCVU> tb_CHUCVU { get; set; }
        public virtual DbSet<tb_LOAINGUOIDUNG> tb_LOAINGUOIDUNG { get; set; }
        public virtual DbSet<tb_LOAITHIETBI> tb_LOAITHIETBI { get; set; }
        public virtual DbSet<tb_NGUOIDUNG> tb_NGUOIDUNG { get; set; }
        public virtual DbSet<tb_NHACUNGCAP> tb_NHACUNGCAP { get; set; }
        public virtual DbSet<TB_NHANTHIETBI> TB_NHANTHIETBI { get; set; }
        public virtual DbSet<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public virtual DbSet<tb_NHAPHANG> tb_NHAPHANG { get; set; }
        public virtual DbSet<tb_PHONGBAN> tb_PHONGBAN { get; set; }
        public virtual DbSet<tb_THIETBI> tb_THIETBI { get; set; }
        public virtual DbSet<tb_TRATHIETBI> tb_TRATHIETBI { get; set; }
        public virtual DbSet<tb_YEUCAUTHIETBI> tb_YEUCAUTHIETBI { get; set; }
    }
}
