//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHITIETNHAPHANG
    {
        public int IDCHITIETNHAPHANG { get; set; }
        public int IDTHIETBI { get; set; }
        public int IDNHAPHANG { get; set; }
        public int SOLUONG { get; set; }
        public double DONGIA { get; set; }
    
        public virtual tb_NHAPHANG tb_NHAPHANG { get; set; }
        public virtual tb_THIETBI tb_THIETBI { get; set; }
    }
}
