//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_NHANTHIETBI
    {
        public int IDNVTB { get; set; }
        [Required(ErrorMessage ="Không được bỏ trống")]
        public int IDNHANVIEN { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDTHIETBI { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNGUOIDUNG { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime NGAYTRA { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public double FineAmount { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<double> ReceiveAmount { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int TONGNGAYDUNG { get; set; }
    
        public virtual tb_NGUOIDUNG tb_NGUOIDUNG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        public virtual tb_THIETBI tb_THIETBI { get; set; }
    }
}
