//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_NHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NHAPHANG()
        {
            this.tb_CHITIETNHAPHANG = new HashSet<tb_CHITIETNHAPHANG>();
        }
    
        public int IDNHAPHANG { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime NGAYNHAP { get; set; }
        public int IDNGUOIDUNG { get; set; }
       
        public double GIA { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNHACUNGCAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHITIETNHAPHANG> tb_CHITIETNHAPHANG { get; set; }
        public virtual tb_NGUOIDUNG tb_NGUOIDUNG { get; set; }
        public virtual tb_NHACUNGCAP tb_NHACUNGCAP { get; set; }
    }
}
