//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_NHACUNGCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NHACUNGCAP()
        {
            this.tb_NHAPHANG = new HashSet<tb_NHAPHANG>();
        }
    
        public int IDNHACUNGCAP { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string TENNHACUNGCAP { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNGUOIDUNG { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string EMAIL { get; set; }
        public string GHICHU { get; set; }
    
        public virtual tb_NGUOIDUNG tb_NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NHAPHANG> tb_NHAPHANG { get; set; }
    }
}
