//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NGUOIDUNG()
        {
            this.tb_CHUCVU = new HashSet<tb_CHUCVU>();
            this.tb_NHACUNGCAP = new HashSet<tb_NHACUNGCAP>();
            this.TB_NHANTHIETBI = new HashSet<TB_NHANTHIETBI>();
            this.tb_NHAPHANG = new HashSet<tb_NHAPHANG>();
            this.tb_PHONGBAN = new HashSet<tb_PHONGBAN>();
            this.tb_THIETBI = new HashSet<tb_THIETBI>();
            this.tb_TRATHIETBI = new HashSet<tb_TRATHIETBI>();
            this.tb_YEUCAUTHIETBI = new HashSet<tb_YEUCAUTHIETBI>();
        }
    
        public int IDNGUOIDUNG { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDLOAINGUOIDUNG { get; set; }
        public string TENNGUOIDUNG { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNHANVIEN { get; set; }

        public bool TINHTRANGHOATDONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHUCVU> tb_CHUCVU { get; set; }
        public virtual tb_LOAINGUOIDUNG tb_LOAINGUOIDUNG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NHACUNGCAP> tb_NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANTHIETBI> TB_NHANTHIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NHAPHANG> tb_NHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PHONGBAN> tb_PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_THIETBI> tb_THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TRATHIETBI> tb_TRATHIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_YEUCAUTHIETBI> tb_YEUCAUTHIETBI { get; set; }
    }
}
