//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_THIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_THIETBI()
        {
            this.PurTemDetailsTables = new HashSet<PurTemDetailsTable>();
            this.tb_CHITIETNHAPHANG = new HashSet<tb_CHITIETNHAPHANG>();
            this.TB_NHANTHIETBI = new HashSet<TB_NHANTHIETBI>();
            this.tb_TRATHIETBI = new HashSet<tb_TRATHIETBI>();
            this.tb_YEUCAUTHIETBI = new HashSet<tb_YEUCAUTHIETBI>();
        }
    
        public int IDTHIETBI { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNGUOIDUNG { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDPHONGBAN { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDLOAITHIETBI { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string TENTHIETBI { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string MOTA { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string XUATXU { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string CAUHINH { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public double SOIP { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int SOLUONG { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime NHAYNHAP { get; set; }
        [DataType(DataType.Currency)]
        public double GIA { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurTemDetailsTable> PurTemDetailsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHITIETNHAPHANG> tb_CHITIETNHAPHANG { get; set; }
        public virtual tb_LOAITHIETBI tb_LOAITHIETBI { get; set; }
        public virtual tb_NGUOIDUNG tb_NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANTHIETBI> TB_NHANTHIETBI { get; set; }
        public virtual tb_PHONGBAN tb_PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TRATHIETBI> tb_TRATHIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_YEUCAUTHIETBI> tb_YEUCAUTHIETBI { get; set; }
    }
}
