//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_YEUCAUTHIETBI
    {
        public int IDYEUCAUTB { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNGUOIDUNG { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDTHIETBI { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int IDNHANVIEN { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int SOLUONG { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime NGAYYEUCAU { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime NGAYTRA { get; set; }
        public bool TRANGTHAI { get; set; }

        public string GHICHU { get; set; }
      
        public bool ReserveNoOfCopies { get; set; }
    
        public virtual tb_NGUOIDUNG tb_NGUOIDUNG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        public virtual tb_THIETBI tb_THIETBI { get; set; }
    }
}
